server:
  port: 8080
#logging:
#  level:
#    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://54.218.80.39:3306/picfood?autoReconnect=true&useSSL=false
    username: myuser
    password: YaleSE2018
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update # validate
#    show-sql: true
  redis:
   port: 6379
   host: 54.218.80.39
  session:
    store-type: redis

