server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  ssl:
    key-alias: pic-food
    key-store-type: PKCS12
    key-password: YaleSE2018
    key-store: classpath:pic-food_com.p12
#logging:
#  level:
#    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://db.pic-food.com:3306/picfood?autoReconnect=true&useSSL=false
    username: myuser
    password: YaleSE2018
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update # validate
#    show-sql: true
  redis:
   port: 6379
   host: db.pic-food.com
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb
amazonProperties:
  region: us-east-1
  endpointUrl: https://s3.us-east-1.amazonaws.com
  accessKey: AKIAJXW4BOPAJT5ZRQJA
  secretKey: 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
  bucketName: picfoodphotos
